/**
 *  存放mutation名称常量
 */

export const CHANGE_HEATMAP_ZOOM = 'CHANGE_HEATMAP_ZOOM';
export const CHANGE_LEFTPANEL_SHOW = 'CHANGE_LEFTPANEL_SHOW';
export const UPDATE_SECTION_INFO = 'UPDATE_SECTION_INFO';
